---
driver:
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  availability_zone: <%= ENV['AWS_AZ'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  instance_type: t2.micro
  image_id: <%= ENV['AWS_AMI_ID'] %>
  security_group_ids: <%= ENV['AWS_SECURITY_GROUP_IDS'] %>

transport:
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>